### PR TITLE
review

### PR DESCRIPTION
**Pull request by BarathMatthew**
Hi sarabudheen please review my code and please update me if there is anything to change

### CODE REVIEW

**Review by Sarabudheen — CHANGES_REQUESTED** [review]
Hi Barath matthew I have verified your code and there are few things need to be update in your code 
**In all your bean class remove the default commands.
**In User Service the unused methods are commanded update it or remove it.
**and do the same in User Controller
Please update it and let me know.

**Comment by BarathMatthew** [comment]
Hi Sarabudheen I have done the changes as per your suggestions and can you update my status.

**Review by Sarabudheen — COMMENTED** [review]
Everything everything is fine in the backend.In fthe front end there is a unused component dashboard please remove it.

**Comment by BarathMatthew** [comment]
Hi sara I have updated the component dashboard can you review it .

**Review by Sarabudheen — APPROVED** [review]
yes matthew everything is fine now.thank you.

**Pull request merged**
